services:
  app:
    container_name: github_ci_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        APP_ENV: testing
    working_dir: /var/www/html
    environment:
      APP_ENV: testing
      QUEUE_CONNECTION: sync
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      meilisearch:
        condition: service_started

  mysql:
    container_name: github_ci_mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: tokoku_ci
      MYSQL_USER: tokoku_ci
      MYSQL_PASSWORD: tokoku_ci
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    container_name: github_ci_redis
    image: redis:7

  meilisearch:
    container_name: github_ci_meilisearch
    image: getmeili/meilisearch:v1.16
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: masterKey
      MEILI_NO_ANALYTICS: "true"
