version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.16
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_NO_ANALYTICS: "true"   # disable telemetry
      MEILI_ENV: "development"     # or "production"
      MEILI_MASTER_KEY: "aSampleMasterKey"  # change this to something secure
    volumes:
      - meili_data:/meili_data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"] # persist data
    volumes:
      - redis_data:/data

volumes:
  meili_data:
  redis_data:
